# Generated by Django 3.2.5 on 2021-08-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectResult',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.TimeField()),
                ('class_field', models.CharField(db_column='class', max_length=45)),
            ],
            options={
                'db_table': 'detect_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('graph', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
    ]
